### ISSUE TITLE
Resolve warning during segmentation about lossy conversion (int64 to uint8)

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#175]
This message (I believe) appears during any segmentation attempt (i.e. Jupyter Notebooks/Python env/command line). The images segment fine, so to resolve this warning message it's just a matter of doing that conversion ourselves instead of letting one of the tools do so implicitly (not sure which one, whichever one throws the warning) .

<img width="812" alt="capture d ecran 2019-03-05 a 11 07 35" src="https://user-images.githubusercontent.com/1421029/53812995-29e2ee80-3f37-11e9-89f3-e8476bfa1436.png">

Could go hand in hand with #170

**Comment by mathieuboudreau** [comment]
Closed because this issue is deprecated since our move to IVADOMED.

**Comment by mariehbourget** [comment]
> I think its on our side.

We also have that message directly in ivadomed, I think it comes from `imageio.imwrite` in [pred_to_png](https://github.com/ivadomed/ivadomed/blob/a58898448b69dddfdccffd8de1694a70d78c900b/ivadomed/inference.py#L215) where the float64 predictions are converted to uint8 of the PNG file.

**Comment by hermancollin** [comment]
@mathieuboudreau @mariehbourget are we sure this is not causing problems? Sometimes I get these 
![Screenshot_20220726_105911](https://user-images.githubusercontent.com/83031821/181040417-dc47367a-f09b-4649-85fd-471377049534.png)
I'd be curious to know where this warning comes from exactly, if you have any insights. Why would these values be in the range `[31.075000762939453, 252.47300720214844]` before being saved?

**Comment by mariehbourget** [comment]
> @mathieuboudreau @mariehbourget are we sure this is not causing problems? Sometimes I get these ![Screenshot_20220726_105911](https://user-images.githubusercontent.com/83031821/181040417-dc47367a-f09b-4649-85fd-471377049534.png) I'd be curious to know where this warning comes from exactly, if you have any insights. Why would these values be in the range `[31.075000762939453, 252.47300720214844]` before being saved?
> 
> In the comments above, we can also see ranges `[0.0, 1.0]` and `[0.0, 255.0]`.

I don't think this is the same as the error in the previous comment. In the previous comment, the message comes from `pred_to_png` (conversion of prediction in float range 0-1 to png 8 bit range 0-255).

In this message, it seems to happens when loading the files, can you show the previous and following line in the screenshot?

**Comment by hermancollin** [comment]
```
2022-07-26 11:05:51.684 | INFO     | AxonDeepSeg.segment:segment_folders:254 - Loading /home/herman/Documents/NEUROPOLY_22/20220726_20x_samples/20220726_vcu_shared_folder/22G-13-33 20x.tif.
Lossy conversion from float32 to uint8. Range [37.064998626708984, 222.81500244140625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [37.064998626708984, 222.81500244140625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [37.064998626708984, 222.81500244140625]. Convert image to uint8 prior to saving to suppress this warning.
2022-07-26 11:05:52.638 | INFO     | ivadomed.config_manager:_display_differing_keys:153 - Adding the following keys to the configuration file
2022-07-26 11:05:52.639 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     loader_parameters: patch_filter_params: {'filter_empty_mask': False, 'filter_empty_input': False}
2022-07-26 11:05:52.639 | INFO     | ivadomed.config_manager:_display_differing_keys:155 - 

2022-07-26 11:05:52.639 | WARNING  | ivadomed.inference:segment_volume:403 - fname_roi has not been specified, then the entire volume is processed.
2022-07-26 11:05:54.932 | INFO     | ivadomed.inference:segment_volume:451 - Loaded 30 axial patches of shape [512, 512].
2022-07-26 11:05:54.996 | INFO     | ivadomed.utils:define_device:131 - Cuda is not available.
2022-07-26 11:05:54.997 | INFO     | ivadomed.utils:define_device:132 - Working on cpu.
2022-07-26 11:05:54.997 | DEBUG    | ivadomed.inference:get_preds:71 - PyTorch model detected at: /home/herman/Documents/NEUROPOLY_21/crypte/20220316_upload_wakehealth_model_on_gh/model_seg_human_axon-myelin_bf/model_seg_human_axon-myelin_bf.pt
2022-07-26 11:05:54.997 | DEBUG    | ivadomed.inference:get_preds:72 - Loading model from: /home/herman/Documents/NEUROPOLY_21/crypte/20220316_upload_wakehealth_model_on_gh/model_seg_human_axon-myelin_bf/model_seg_human_axon-myelin_bf.pt
2022-07-26 11:05:55.032 | DEBUG    | ivadomed.inference:get_preds:75 - Evaluating model: /home/herman/Documents/NEUROPOLY_21/crypte/20220316_upload_wakehealth_model_on_gh/model_seg_human_axon-myelin_bf/model_seg_human_axon-myelin_bf.pt
2022-07-26 11:06:31.050 | DEBUG    | ivadomed.inference:get_preds:92 - Sending predictions to CPU
```

Looks like it happens when the image is loaded. In that case, maybe I should normalize the images before the segmentation.

**Comment by mathieuboudreau** [comment]
Are they loaded using our ads `imread` function? Maybe we'll need to add a flag to explicitely pass the bitdepth through the function if so?

https://github.com/axondeepseg/axondeepseg/blob/9ab79c339189149e52da237f9fd20436b313bce1/AxonDeepSeg/ads_utils.py#L257-L284

**Comment by mathieuboudreau** [comment]
*since we're passing 8 bit by default, not 100% sure this is where you're seeing the issue but it might be.

**Comment by hermancollin** [comment]
@mathieuboudreau looks like our imread function:
```
>>> from AxonDeepSeg import ads_utils as adsu
>>> im = adsu.imread('20220726_vcu_shared_folder/22G-13-15 20x.tif')
Lossy conversion from float32 to uint8. Range [31.075000762939453, 252.47300720214844]. Convert image to uint8 prior to saving to suppress this warning.
```

**Comment by mathieuboudreau** [comment]
Hum no, that proposed solution didn't work for me locally, will think about this more.


```

(ads_venv) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % axondeepseg -t SEM -i AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/image.png
2022-07-26 15:12:05.352 | INFO     | AxonDeepSeg.segment:main:323 - AxonDeepSeg v.4.0.0
2022-07-26 15:12:05.508 | ERROR    | AxonDeepSeg.segment:main:469 - An error has been caught in function 'main', process 'MainProcess' (96052), thread 'MainThread' (8643888640):
Traceback (most recent call last):

  File "/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/bin/axondeepseg", line 33, in <module>
    sys.exit(load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg')())
    │   │    └ <function importlib_load_entry_point at 0x7fe2700461f0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

> File "/Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/segment.py", line 469, in main
    segment_image(
    └ <function segment_image at 0x7fe279c1ed30>

  File "/Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/segment.py", line 168, in segment_image
    im = ads.imread(path_testing_image)
         │   │      └ PosixPath('/Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/ima...
         │   └ <function imread at 0x7fe2a0619670>
         └ <module 'AxonDeepSeg.ads_utils' from '/Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/ads_utils.py'>

  File "/Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/ads_utils.py", line 284, in imread
    img = imageio.core.image_as_uint(img_as_ubyte(raw_img), bitdepth=bitdepth)
          │       │    │             │            │                  └ 8
          │       │    │             │            └ Array([[201., 199., 201., ..., 195., 191., 181.],
          │       │    │             │                     [207., 220., 227., ..., 176., 174., 167.],
          │       │    │             │                     [218., 222., 217.,...
          │       │    │             └ <function img_as_ubyte at 0x7fe2705219d0>
          │       │    └ <function image_as_uint at 0x7fe2704c2c10>
          │       └ <module 'imageio.core' from '/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/lib/python3.8/site-packages/imageio/core/__in...
          └ <module 'imageio' from '/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/lib/python3.8/site-packages/imageio/__init__.py'>

  File "/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/lib/python3.8/site-packages/skimage/util/dtype.py", line 531, in img_as_ubyte
    return _convert(image, np.uint8, force_copy)
           │        │      │  │      └ False
           │        │      │  └ <class 'numpy.uint8'>
           │        │      └ <module 'numpy' from '/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/lib/python3.8/site-packages/numpy/__init__.py'>
           │        └ Array([[201., 199., 201., ..., 195., 191., 181.],
           │                 [207., 220., 227., ..., 176., 174., 167.],
           │                 [218., 222., 217.,...
           └ <function _convert at 0x7fe2705215e0>
  File "/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/lib/python3.8/site-packages/skimage/util/dtype.py", line 283, in _convert
    raise ValueError("Images of type float must be between -1 and 1.")

ValueError: Images of type float must be between -1 and 1.
```
