### ISSUE TITLE
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#251]
After fresh installation of ADS (this commit: https://github.com/neuropoly/axondeepseg/commit/fdb2c8c60d1986fed0c703e862c0f3c22d0ca854) on OSX Mojave, when running `axondeepseg_test` I get the following TF exception:

~~~
* * * Integrity test passed. AxonDeepSeg is correctly installed. * * * 
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x13b9fde48>>
Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
~~~

**Comment by mathieuboudreau** [comment]
Closed, stale.
