### ISSUE TITLE
Problem using plugin if there was an error before

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#255]
After experiencing an error with the FSLeyes plugin, when trying to re-use it (e.g. load new image, click on "prediction"), the following error message appears:

<details>

~~~
(ads_venv) julien-macbook:~ $ Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/profiles/__init__.py", line 1316, in __onEvent
    self.__profile.handleEvent(ev)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/profiles/__init__.py", line 789, in handleEvent
    handler(ev)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/profiles/__init__.py", line 1137, in __onMouseUp
    if handler(ev, canvas, mouseLoc, canvasLoc) is False:
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/profiles/__init__.py", line 980, in handlerWrapper
    retval = defHandler(*args, **kwargs)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/profiles/orthoeditprofile.py", line 1511, in _selModeLeftMouseUp
    restrict      = [slice(o, o + s) for o, s in zip(off, new.shape)]
AttributeError: 'NoneType' object has no attribute 'shape'
Loading acquisitions ...
Rescaling acquisitions to the target resolution ...
Graph construction ...
Beginning inference ...
processing patch 1 of 1
Traceback (most recent call last):
  File "/Users/julien/.fsleyes/plugins/ads_plugin.py", line 319, in on_apply_model_button
    verbosity_level=3
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 276, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 130, in apply_convnet
    prediction_proba_activate=prediction_proba_activate)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 480, in perform_batch_inference
    p = model.predict(batch_x)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (512, 512, 3) but got array with shape (145, 144, 3)
Loading acquisitions ...
Rescaling acquisitions to the target resolution ...
Graph construction ...
2019-09-03 12:52:34.032598: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py:83) ]]

Caused by op 'save_1/RestoreV2', defined at:
  File "/Users/julien/miniconda3/envs/ads_venv/bin/fsleyes", line 11, in <module>
    sys.exit(main())
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/main.py", line 422, in main
    app.MainLoop()
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/wx/core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/Users/julien/.fsleyes/plugins/ads_plugin.py", line 319, in on_apply_model_button
    verbosity_level=3
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 276, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 83, in apply_convnet
    saver = tf.train.Saver()  # Load previous model
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py:83) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/.fsleyes/plugins/ads_plugin.py", line 319, in on_apply_model_button
    verbosity_level=3
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 276, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 95, in apply_convnet
    saver.restore(sess, str(model_previous_path))
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py:83) ]]

Caused by op 'save_1/RestoreV2', defined at:
  File "/Users/julien/miniconda3/envs/ads_venv/bin/fsleyes", line 11, in <module>
    sys.exit(main())
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/fsleyes/main.py", line 422, in main
    app.MainLoop()
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/wx/core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/Users/julien/.fsleyes/plugins/ads_plugin.py", line 319, in on_apply_model_button
    verbosity_level=3
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 276, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py", line 83, in apply_convnet
    saver = tf.train.Saver()  # Load previous model
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/julien/miniconda3/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key cconv-d0-c0_1/convolution/batch_normalization_25/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /Users/julien/code/axondeepseg/AxonDeepSeg/apply_model.py:83) ]]
~~~

</details>

TODO: add more info about the reproducibility of this bug. Do more tests...

**Comment by mathieuboudreau** [comment]
Closed, stale. Works fine now.
