### ISSUE TITLE
imread bug when "tif" is present in filename

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#618]
**Describe the bug**

While debugging for #617, I found an issue with [ads_utils.py/imread](https://github.com/axondeepseg/axondeepseg/blob/ca4baad96bed0d9c84b2dc63a8c4b464dc4d5a2c/AxonDeepSeg/ads_utils.py#L254).

The condition to use tiff-pil to open TIF files is `if 'tif' in str(filename):`.
This fails when the file is not a tif, but the letter `tif` are present anywhere in the path of the file.
We should use a "endswith" condition instead (for `.tif `and `.tiff`) or an exact match after splitting the filename at the last dot.

Note: this can be addressed independently from #617 on ADS side.

**To Reproduce**
- Rename any image (png or tif 8bit) with `tif` in the filename, ex: `tifabcd.png`
- Run the segmentation with ADS CLI.
- The error message comes from `merge_masks` which is trying to use `imread` to read the "tifabcd_seg-axon.png" and "tifabcd_seg-myelin.png" segmentation files but fails because it's using tif-pill to open a PNG.

```
Traceback (most recent call last):
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/core/imopen.py", line 188, in imopen
    return loader(request, **kwargs)
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/core/imopen.py", line 177, in loader
    return config.plugin_class(request, **kwargs)
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/core/legacy_plugin_wrapper.py", line 69, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `TIFF-PIL` can not read `/home/mhbourget/Documents/20220316-16bit/tifabcd_seg-axon.png`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/bin/axondeepseg", line 33, in <module>
    sys.exit(load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg')())
  File "/home/mhbourget/code/axondeepseg/AxonDeepSeg/segment.py", line 276, in main
    segment_image(
  File "/home/mhbourget/code/axondeepseg/AxonDeepSeg/segment.py", line 112, in segment_image
    axon_segmentation(path_acquisitions_folders=path_acquisition, acquisitions_filenames=[str(path_acquisition / acquisition_name)],
  File "/home/mhbourget/code/axondeepseg/AxonDeepSeg/apply_model.py", line 56, in axon_segmentation
    merge_masks(
  File "/home/mhbourget/code/axondeepseg/AxonDeepSeg/visualization/merge_masks.py", line 12, in merge_masks
    axon = ads.imread(path_axon)
  File "/home/mhbourget/code/axondeepseg/AxonDeepSeg/ads_utils.py", line 259, in imread
    raw_img = imageio.imread(filename, format='tiff-pil')
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/__init__.py", line 86, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/v2.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "/home/mhbourget/miniconda/envs/ads_venv_v4/lib/python3.8/site-packages/imageio/core/imopen.py", line 206, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `tiff-pil` can not handle the given uri.
```

**Comment by Stoyan-I-A** [comment]
> We should use a "endswith" condition instead (for `.tif `and `.tiff`) or an exact match after splitting the filename at the last dot.

To add a better solution: create a parameter with all the "valid extensions", kind of like what I tried to do [in the ads_plugin](https://github.com/axondeepseg/axondeepseg/blob/ca4baad96bed0d9c84b2dc63a8c4b464dc4d5a2c/ads_plugin.py#L315). and make sure the extension of the file we try to segment has a valid extension. The list of valid extensions could be added to config.py or params.py (which are two files that kind of have the same purpose so they could be merged in one file).

**Comment by mariehbourget** [comment]
> To add a better solution: create a parameter with all the "valid extensions", kind of like what I tried to do [in the ads_plugin](https://github.com/axondeepseg/axondeepseg/blob/ca4baad96bed0d9c84b2dc63a8c4b464dc4d5a2c/ads_plugin.py#L315). and make sure the extension of the file we try to segment has a valid extension.

Great point!
For the file we try to segment, the check is done in ivadomed  [here](https://github.com/ivadomed/ivadomed/blob/1a3d193922938dc35e9eb77d6af7fd8e6d1bacfa/ivadomed/loader/segmentation_pair.py#L281).

But I agree, it would be good to have the check done in ADS for the imread function in general.
