### ISSUE TITLE
axondeepseg does not work on python 3.12 as of June 2024. 

### ISSUE THREAD

**Issue by dccote** [axondeepseg/axondeepseg#807]
`pip3.12 install axondeepseg` fails with module imp missing.  The setup.py file should be updated for ≤ 3.11.
 
 ```
Collecting axondeepseg
  Using cached AxonDeepSeg-2.1-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting numpy==1.14.5 (from axondeepseg)
  Using cached numpy-1.14.5.zip (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy==1.1.0 (from axondeepseg)
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d0/x8hs1rf515z3h1d_nfwynry00000gn/T/pip-build-env-9ltpf42i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d0/x8hs1rf515z3h1d_nfwynry00000gn/T/pip-build-env-9ltpf42i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/d0/x8hs1rf515z3h1d_nfwynry00000gn/T/pip-build-env-9ltpf42i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/d0/x8hs1rf515z3h1d_nfwynry00000gn/T/pip-build-env-9ltpf42i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 474, in <module>
        File "<string>", line 398, in setup_package
        File "<string>", line 138, in write_version_py
        File "<string>", line 114, in get_version_info
      ModuleNotFoundError: No module named 'imp'
      [end of output]
```

**Comment by mathieuboudreau** [comment]
@dccote our pip packages are no longer supported / maintained, I've opened an issue to resolve this so that users don't attempt to install ADS via pip anymore where they would encounter your issue (#808).

Thanks for pointing this out!
